version: '3.3'
services: 
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: task_managment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=#Notroot1
    ports:
      - 5050:80
    depends_on:
      - db

  api:
    container_name: task-mgmt
    image: task_mgmt:latest
    volumes: 
      - ./api:/api
    env_file:
      - ./api/.env
    ports: 
      - 8000:80
    restart: always
    environment:
      - WATCHFILES_FORCE_POLLING=true
    depends_on:
      - db